version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=calendar
    volumes:
      - .:/backend  # Mount the current directory to /app in the container
      - /backend/node_modules  # Ensure node_modules is not overwritten

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ main port
      - "15672:15672"    # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   # Persist RabbitMQ data    

volumes:
  db_data:
  rabbitmq_data: